ALTER TABLE IF EXISTS bills ALTER COLUMN invoice_url TYPE TEXT;
ALTER TABLE IF EXISTS bills ALTER COLUMN payment_link TYPE TEXT;
ALTER TABLE IF EXISTS bills ALTER COLUMN pix_qr_code_image TYPE TEXT;
ALTER TABLE IF EXISTS bills ALTER COLUMN pix_copy_paste TYPE TEXT;
